### ISSUE TITLE
Clean geometries before run

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#12]
```
_core.QgsProcessingException: There were errors executing the algorithm.
Traceback (most recent call last):
  File "/home/tiago_marques/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 405, in run
    'INTERSECT': studyAreaLayer, 'OUTPUT': outputFile, 'PREDICATE': [0]})
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 105, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 183, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: There were errors executing the algorithm.
```

**Comment by gioman** [comment]
Apparently due to geometry errors in the land use layer.

**Comment by gioman** [comment]
Not being able to replicate on a different laptop.

**Comment by gioman** [comment]
Adding a sample layer that possibly was the cause.

[area_estudo.gpkg.zip](https://github.com/NaturalGIS/mapping_ecosystem_services/files/3898309/area_estudo.gpkg.zip)

**Comment by lcalisto** [comment]
Humm yes. Let's try to fix the geometries using qgis "fix geometries" before we actually process them! What do you think?

**Comment by gioman** [comment]
> Humm yes. Let's try to fix the geometries using qgis "fix geometries" before we actually process them! What do you think?


@lcalisto If is a reasonable amount of work I would say yes, let's pass the inputs through the "fix geometries" QGIS tool, given this tool is exposed through the API. If you can't confirm the error with the above vector we can change this to a feature request rather than bug.

**Comment by lcalisto** [comment]
No worries this should be possible. I'll try.

**Comment by gioman** [comment]
If implemented this needs to be optional (with a checkbox).
