### ISSUE TITLE
Block "ok" button unless all mandatory inputs are set

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#5]
Otherwise a python error is thrown

IndexError: list index out of range 
Traceback (most recent call last):
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 384, in run
    studyAreaLayer = self.getSelectedStudyAreaLayer()
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 249, in getSelectedStudyAreaLayer
    return QgsProject.instance().mapLayersByName(selectedStudyArea)[0]
IndexError: list index out of range

**Comment by lcalisto** [comment]
This issue should be fixed can you please test?

**Comment by gioman** [comment]
@lcalisto ok! but better complete it with https://github.com/NaturalGIS/mapping_ecosystem_services/issues/33

**Comment by lcalisto** [comment]
I agree!
