### ISSUE TITLE
Python error if project has groups in it

### ISSUE THREAD

**Issue by gioman** [NaturalGIS/mapping_ecosystem_services#8]
Does not seems to block the usage the plugin anyway.

As seen on QGIS 3.4 on Linux.

```
AttributeError: 'QgsLayerTreeGroup' object has no attribute 'layer' 
Traceback (most recent call last):
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 339, in run
    layers = [layer for layer in layers if (layer.layer().type() == 0)]
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 339, in 
    layers = [layer for layer in layers if (layer.layer().type() == 0)]
AttributeError: 'QgsLayerTreeGroup' object has no attribute 'layer
```

**Comment by gioman** [comment]
@lcalisto this happens when the project has groups in the layer list.

**Comment by gioman** [comment]
@lcalisto this also prevents to use as input layers that are in a group.

**Comment by lcalisto** [comment]
Fixed. Please test

**Comment by gioman** [comment]
@lcalisto now an error show even if the project has no groups in it, then in de plugin GUI is not possible to select any layer as input

```
IndexError: list index out of range 
Traceback (most recent call last):
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 343, in run
    layers = self.getLayers()
  File "/home/giovanni/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mapping_ecosystem_services-master/mapping_ecosystem_services.py", line 218, in getLayers
    projectLayers.extend([layer for layer in groupedLayers[0] if (
IndexError: list index out of range
```

**Comment by lcalisto** [comment]
ups, it was a very a stupid bug! sorry! Should be fixed, can you test?
